### ISSUE TITLE
OS X and windows builds are failing on master. No build for libgfortran>=4.0.0 is available.

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/arpack-feedstock#33]
cc @isuruf I see you merged the last PR into master.

**Comment by isuruf** [comment]
I don't see any failed builds. Can you give a link?

**Comment by SylvainCorlay** [comment]
top commits in the master branch: https://github.com/conda-forge/arpack-feedstock/commits/master

**Comment by isuruf** [comment]
Ah, those are azure builds. appveyor and travis work fine

**Comment by SylvainCorlay** [comment]
Oh yes, that is right.

Weird that I am getting that conflict in package versions then. Closing. Will open another issue about the conflicting specs.
